export enum AuditAction {
    CREATED = 'CREATED',
    SUBMITTED = 'SUBMITTED',
    APPROVED = 'APPROVED',
    REJECTED = 'REJECTED',
    DELETED = 'DELETED',

    PASSWORD_CHANGED = 'PASSWORD_CHANGED',
    PASSWORD_RESEST = 'PASSWORD-RESET',
    USER_CREATED = 'USER_CREATED',

    GET = 'GET',
    UPLOADATTACHMENT = 'UPLOADATTACHMENT',

    LOGIN = 'LOGIN',
}